### PR TITLE
fix: add optional env variable to force use nvm

### PR DESCRIPTION
**Pull request by spsjvc**

### CODE REVIEW

**Comment by DZGoldman** [comment]
do we also need to explictly set the path? 
```
 FORCE_USE_NVM=true arb-token-lists/update_all ./arb-token-lists 
```
(from my root dir) fails with 
```
 Couldn't find a package.json file in "/Users/me
```
(i think this is the right way to test it)

**Comment by DZGoldman** [comment]
like do we need a combo of this and [this](https://github.com/OffchainLabs/arb-token-lists/pull/48) maybe?

**Review by DZGoldman — CHANGES_REQUESTED** [review]
(see above)

**Comment by spsjvc** [comment]
Hmm, in the cron task I made a change to `cd arb-token-lists && ./update_all`. Can you try that? @DZGoldman

**Comment by DZGoldman** [comment]
@spsjvc ah okay that works too, lgtm

**Review by DZGoldman — APPROVED** [review]

**Pull request merged**
